version: "3.9"

services:

  frontend:
    build:
      context: ./frontend

    container_name: pantrypal_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

    depends_on:
      - backend

    restart: unless-stopped


  backend:
    build:
      context: ./backend

    container_name: pantrypal_backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/backend

    environment:
      AWS_BEARER_TOKEN_BEDROCK: YOUR_TOKEN_HERE

    restart: unless-stopped